version: '3.1'

services:

    db:
        container_name: db
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        networks:
            jbsite:

    phpmyadmin:
        depends_on: 
            - db
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: 
            - '8081:80'
        links:
            - db:db
        environment: 
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: pass
        networks:
            jbsite:

    apache:
        container_name: php-apache
        build: .
        restart: always
        volumes: ['./www:/var/www/html']
        ports:
            - '80:80'
        links:
            - db
        networks:
            jbsite:
        
networks:
    jbsite:
